import type { AppContext } from "../../../context-app.ts";

export type WhatnotApp = Pick<
  AppContext,
  | "activeScopeType"
  | "activeWorkspaceId"
  | "askConfirmation"
  | "googleAuthEpoch"
  | "hasProAccess"
  | "isCurrentWorkspaceOwner"
  | "notify"
  | "preferredLanguage"
  | "whatnotConnectionStatus"
  | "whatnotSyncStatus"
  | "whatnotConnectionSummary"
  | "whatnotCsvRawInput"
  | "whatnotCsvSellerAccountId"
  | "whatnotCsvHeaders"
  | "whatnotCsvRows"
  | "whatnotCsvMapExternalSaleId"
  | "whatnotCsvMapOrderId"
  | "whatnotCsvMapOrderItemId"
  | "whatnotCsvMapSellerAccountId"
  | "whatnotCsvMapTitle"
  | "whatnotCsvMapListingTitle"
  | "whatnotCsvMapBuyerName"
  | "whatnotCsvMapOrderPlacedAt"
  | "whatnotCsvMapOriginalItemPrice"
  | "whatnotCsvMapSku"
  | "whatnotCsvMapProductCategory"
  | "whatnotCsvMapQuantity"
  | "whatnotCsvMapPrice"
  | "whatnotCsvMapBuyerShipping"
  | "whatnotCsvMapDate"
  | "whatnotCsvMapOrderStatus"
  | "whatnotReviewBatchId"
  | "whatnotReviewRows"
  | "isConfirmingWhatnotImport"
  | "whatnotConfirmationRetryPayload"
  | "showWhatnotCsvImportDialog"
  | "showWhatnotReviewDialog"
  | "whatnotCallbackStatus"
  | "whatnotCallbackMessage"
  | "pullCloudSync"
  | "currentLotId"
  | "sales"
  | "getSalesStorageKey"
>;
