export const ShopifyErrorCode = {
  PREVIEW_STALE: "SHOPIFY_PREVIEW_STALE", PRICE_REQUIRED: "SHOPIFY_PRICE_REQUIRED",
  CURRENCY_MISMATCH: "SHOPIFY_CURRENCY_MISMATCH", INVENTORY_INVALID: "SHOPIFY_INVENTORY_INVALID",
  LOCATION_REQUIRED: "SHOPIFY_LOCATION_REQUIRED", LOT_UNAVAILABLE: "SHOPIFY_LOT_UNAVAILABLE",
  ALREADY_LINKED: "SHOPIFY_ALREADY_LINKED", CONNECTION_CHANGED: "SHOPIFY_CONNECTION_CHANGED",
  DETAILS_CHANGED: "SHOPIFY_DETAILS_CHANGED",
  BINDING_CHANGED: "SHOPIFY_BINDING_CHANGED", VARIANT_ALREADY_BOUND: "SHOPIFY_VARIANT_ALREADY_BOUND"
} as const;
export type ShopifyErrorCode = typeof ShopifyErrorCode[keyof typeof ShopifyErrorCode];
export const shopifyErrorCodeSet = new Set<string>(Object.values(ShopifyErrorCode));
